### ISSUE TITLE
Errors in S1C88_InstructionSet.md

### ISSUE THREAD

**Issue by nanoni17728** [logicplace/pm-dev-docs#1]
Since there is a lot of instructions to check I opened an issue to keep track of what I already checked and what errors there are. I’ll correct them afterwards.

If you want to help post here the error to correct and a screenshot of the instruction from the [official documentation](https://discord.com/channels/549770771963314216/549781558412836875/947203489728180246).

Current progress:

- [ ] 8-bit arithmetic and logic operations
- [x] 8-bit transfer
- [ ] Rotate/shift
- [x] Auxiliary operations
- [ ] 16-bit arithmetic operations
- [ ] 16-bit transfer
- [ ] Stack Control
- [ ] Branch
- [ ] System Control

## 8-bit transfer

The LD instructions for NB to YP have incorrect cycles/bytes values.

![LD-1](https://user-images.githubusercontent.com/37584624/155894020-7845ebda-27ff-4088-885d-2887f4c8e521.png)

No further report for 8-bit transfer.

**Comment by logicplace** [comment]
Closing this since you've disappeared, feel free to reopen. Reported issues so far were addressed.
